[package]
name = "topn"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
coinmarketcap_top100_bot = { path = "../../.." }
lambda_http = "0.13"
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
